name: Auto merge
on: workflow_call

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    if: github.event.pull_request.draft == false
    steps:
    - name: auto-merge
      id: auto-merge
      run: gh pr merge --auto --rebase $PR_URL
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_DEBUG: 1
